### ISSUE TITLE
Questions about inclusion in other packages

### ISSUE THREAD

**Issue by dada513** [Admicos/minecraft-wayland#17]
Hey, I’m the maintainer of the [PolyMC Flatpak](https://flathub.org/apps/details/org.polymc.PolyMC). PolyMC is a fork of multimc that aims to implement features the multimc maintainer didn’t want to include and to allow repackaging and system wide installs
 
 im working on including it in the flatpak to support wayland properly and I have a few questions:
1) are you fine with me including your patches there?
2) does libdecor branch work with KDE and other DE’s? I need to support gnome but also others. Don’t care if it’s native decorations. Currently I’m using libdecor branch

**Comment by Admicos** [comment]
> are you fine with me including your patches there?

I personally don't really mind what you do with this, though especially with the libdecor branch you are including a possibly unstable version of glfw (a older snapshot of their `master` branch), with likely unstable patches on top.

> does libdecor branch work with KDE and other DE’s? I need to support gnome but also others. Don’t care if it’s native decorations. Currently I’m using libdecor branch

Aside from Minecraft crashing when you try to close it, KDE works well enough. I haven't tested this outside sway, KDE, or GNOME though, other desktops might have issues.

**Comment by dada513** [comment]
> > are you fine with me including your patches there?
> 
> I personally don't really mind what you do with this, though especially with the libdecor branch you are including a possibly unstable version of glfw (a older snapshot of their `master` branch), with likely unstable patches on top.
> 
> > does libdecor branch work with KDE and other DE’s? I need to support gnome but also others. Don’t care if it’s native decorations. Currently I’m using libdecor branch
> 
> Aside from Minecraft crashing when you try to close it, KDE works well enough. I haven't tested this outside sway, KDE, or GNOME though, other desktops might have issues.

Ok, thanks. The patches are completely optional, but I decided including them and allowing users to enable while being warned is best, as having an unstable version of glfw is still better than screen tearing and glitches on XWayland
