### ISSUE TITLE
Patches 0001 and 0002 are obsolete

### ISSUE THREAD

**Issue by mazunki** [Admicos/minecraft-wayland#19]
`0001-Wayland-Set-O_NONBLOCK-on-repeat-timerfd.patch` is already upstream:

https://github.com/glfw/glfw/commit/963e728881d7551aab0b843c79915f2419d4d36e

On Gentoo, this now breaks the build. Simply removing that file from the list of patches fixes the problem.

**Comment by mazunki** [comment]
After trying to PR this change, I had to fast forward. I see that the same applies for `0002-Wayland-Continue-poll-if-timerfd-can-t-be-read.patch`, as noted here: 

https://github.com/glfw/glfw/pull/1711#issuecomment-993300843

**Comment by Admicos** [comment]
Closed with #20
