### ISSUE TITLE
How to fix weird Frames in the Window? (Fullscreen also affected)

### ISSUE THREAD

**Issue by MSandro** [Admicos/minecraft-wayland#23]
![image](https://user-images.githubusercontent.com/10937159/170246057-9f41b9c5-e2b0-4ebd-a568-d899435df285.png)

**Comment by MSandro** [comment]
maybe it is because of my WQHD Screen? So a HighDPI Issue?
![image](https://user-images.githubusercontent.com/10937159/170246390-5ba19d88-9258-40e5-89e5-ff846dbd906b.png)

**Comment by Admicos** [comment]
use the libdecoration branch

**Comment by MSandro** [comment]
sorry yes I was able to solve it by installing the glfw-wayland-minecraft-libdecoration package
thanks
