### ISSUE TITLE
PolyMC Flatpak Support

### ISSUE THREAD

**Issue by tobfos2611** [Admicos/minecraft-wayland#24]
Flatpak support would be awesome so that I can use this with PolyMC flatpak.

**Comment by Admicos** [comment]
That's up to the PolyMC maintainers.

They had this included for some time, but they seem to have dropped it because it was too big (https://github.com/flathub/org.polymc.PolyMC/issues/19), maybe they'll include it again, maybe they won't.

**Comment by tobfos2611** [comment]
Okay thanks for pointing me in the right direction.
