### ISSUE TITLE
Ubuntu support?

### ISSUE THREAD

**Issue by kristibektashi** [Admicos/minecraft-wayland#26]

**Comment by Admicos** [comment]
I don't maintain any other package other than the PKGBUILD (mainly because I don't use other distros most of the time), so I can't package it for Ubuntu.

But, if someone else packaged it for Ubuntu, I have no reasons why it *wouldn't* work.

**Comment by kristibektashi** [comment]
> I don't maintain any other package other than the PKGBUILD (mainly because I don't use other distros most of the time), so I can't package it for Ubuntu.
> 
> But, if someone else packaged it for Ubuntu, I have no reasons why it _wouldn't_ work.

How do I install on Ubuntu myself?
