### ISSUE TITLE
openSUSE Package

### ISSUE THREAD

**Issue by DimiDimit** [Admicos/minecraft-wayland#3]
FYI, I made an openSUSE package for this: https://build.opensuse.org/package/show/home:DimiDimit/libglfw3-wayland-minecraft
Like the regular one that ships with openSUSE, it neither provides anything in `/usr/lib`, nor `/usr/lib64/libglfw.so` without `.3`, so MultiMC fails to find it by default and you need to add `-Dorg.lwjgl.glfw.libname=/usr/lib64/libglfw.so.3`.

**Comment by Admicos** [comment]
Thanks, added a link to the README file. I'll be keeping this issue open for openSUSE-specific discussion.

**Comment by Admicos** [comment]
Just wanted to notify you the underlying GLFW version has updated to 3.3.6

(Your package seems to not have been updated since the initial release, if you have an RSS reader you might want to subscribe to the commit feed: https://github.com/Admicos/minecraft-wayland/commits.atom)

**Comment by DimiDimit** [comment]
Yeah, I kinda stopped using openSUSE...
