### ISSUE TITLE
Add `patch` dependency to `PKGBUILD`

### ISSUE THREAD

**Issue by Blacksmoke16** [Admicos/minecraft-wayland#49]
The package depends on it, but it is not defined as a dependency so I got `PKGBUILD: line 38: patch: command not found` during the install given it wasn't already installed.

**Comment by JamiKettunen** [comment]
[`base-devel`](https://archlinux.org/packages/core/any/base-devel/) has `patch` in `depends`, [which you should have installed to operate AUR](https://wiki.archlinux.org/title/Arch_User_Repository#Getting_started). I don't like that rule but it is what it is, stuff in `base-devel` that are "missing" from PKGBUILDs are not a bug.

**Comment by Blacksmoke16** [comment]
Ah gotcha, well in that case i'll prob just install that and call it a day. Thanks!
